sonar.projectKey=xisayx_eatly-develop
sonar.organization=xisayx
sonar.projectName=eatly-develop
sonar.sources=app,config,database,resources/js,routes
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,tests/**
sonar.sourceEncoding=UTF-8
sonar.php.version=8.2
